version: 2

workflows:
  version: 2
  stack_build:
    jobs:
      - "lts-11"
      - "lts-12"
      - "lts-14"

shared: &shared
  steps:
    - checkout
    - run: stack --version
    - run: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
    - run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps

jobs:
  "lts-11":
    <<: *shared
    environment.ARGS: "--resolver lts-11.0"
    docker: [image: "fpco/stack-build:lts-11.0"]
  "lts-12":
    <<: *shared
    environment.ARGS: "--resolver lts-12.0"
    docker: [image: "fpco/stack-build:lts-12.0"]
  "lts-14":
    <<: *shared
    environment.ARGS: "--resolver lts-14.0"
    docker: [image: "fpco/stack-build:lts-14.0"]
